### ISSUE TITLE
how to stop watching

### ISSUE THREAD

**Issue by mmclau14** [Axosoft/nsfw#13]
hi, is there any way to stop watching files with this module? docs are lacking or perhaps i'm not seeing them

**Comment by jgrosso** [comment]
https://github.com/Axosoft/nsfw/blob/master/js/src/index.js#L26 seems like it might be a good starting point....

**Comment by implausible** [comment]
```javascript
nsfw('arbitrary/file/path', () => {})
  .then(watch => watch.start()
    .then(() => watch.stop())
  );
```

**Comment by implausible** [comment]
Definitely missing in the documentation. Woops!

**Comment by maxkorp** [comment]
https://github.com/Axosoft/nsfw/pull/14

**Comment by implausible** [comment]
https://github.com/Axosoft/nsfw/tree/master/docs

**Comment by mmclau14** [comment]
perfect. thanks!
