### ISSUE TITLE
Installation issues

### ISSUE THREAD

**Issue by coderZev** [Axosoft/nsfw#161]
Trying to install, receiving error results below. Note: I am using Windows 10.
Please note that this is my first node project so this may not be an issue with nsfw but with my own understanding of how to install :)

C:\Users\zev>npm install Axosoft/nsfw
npm ERR! code ENOENT
npm ERR! syscall spawn git
npm ERR! path git
npm ERR! errno -4058
npm ERR! enoent Error while executing:
npm ERR! enoent undefined ls-remote -h -t ssh://git@github.com/Axosoft/nsfw.git
npm ERR! enoent
npm ERR! enoent
npm ERR! enoent spawn git ENOENT
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\zev\AppData\Roaming\npm-cache\_logs\2022-04-27T20_31_30_653Z-debug.log

C:\Users\zev>

<contents of C:\Users\zev\AppData\Roaming\npm-cache\_logs\2022-04-27T20_27_32_186Z-debug.log >

0 info it worked if it ends with ok
1 verbose cli [
1 verbose cli   'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Users\\zev\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'install',
1 verbose cli   'Axosoft/nsfw'
1 verbose cli ]
2 info using npm@6.14.5
3 info using node@v18.0.0
4 verbose config Skipping project config: C:\Users\zev/.npmrc. (matches userconfig)
5 verbose npm-session 1e73ec87abf2b4ba
6 silly install loadCurrentTree
7 silly install readLocalPackageData
8 silly fetchPackageMetaData error for github:Axosoft/nsfw Error while executing:
8 silly fetchPackageMetaData undefined ls-remote -h -t ssh://git@github.com/Axosoft/nsfw.git
8 silly fetchPackageMetaData
8 silly fetchPackageMetaData
8 silly fetchPackageMetaData spawn git ENOENT
9 timing stage:rollbackFailedOptional Completed in 1ms
10 timing stage:runTopLevelLifecycles Completed in 133ms
11 verbose stack Error: spawn git ENOENT
11 verbose stack     at ChildProcess._handle.onexit (node:internal/child_process:283:19)
11 verbose stack     at onErrorNT (node:internal/child_process:476:16)
11 verbose stack     at process.processTicksAndRejections (node:internal/process/task_queues:82:21)
12 verbose cwd C:\Users\zev
13 verbose Windows_NT 10.0.19044
14 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\zev\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "install" "Axosoft/nsfw"
15 verbose node v18.0.0
16 verbose npm  v6.14.5
17 error code ENOENT
18 error syscall spawn git
19 error path git
20 error errno -4058
21 error enoent Error while executing:
21 error enoent undefined ls-remote -h -t ssh://git@github.com/Axosoft/nsfw.git
21 error enoent
21 error enoent
21 error enoent spawn git ENOENT
22 error enoent This is related to npm not being able to find a file.
23 verbose exit [ -4058, true ]

**Comment by julianmesa-gitkraken** [comment]
Try
`npm i nsfw`
https://www.npmjs.com/package/nsfw
