### ISSUE TITLE
Crash when deleting folder

### ISSUE THREAD

**Issue by gdavidkov** [Axosoft/nsfw#169]
Hello,
We are using the package within the Electron application.
The OS is Windows 10
Scenario: When the folder is deleted but the Windows OS dialog "Folder Access Denied" appears.
Always reproducible.
The dialog:
![nsfw_callstack_2](https://user-images.githubusercontent.com/5815794/200308363-525727bb-57e8-4374-8bab-41c08ca8e6c1.PNG)
Stacktrace: 
![image](https://user-images.githubusercontent.com/5815794/200308285-93d1d1df-3b58-419e-9cfb-b17131c3951e.png)

**Comment by julianmesa-gitkraken** [comment]
@gdavidkov Can you check if this PR fix your issue?

**Comment by gdavidkov** [comment]
It works. I've received the following error: Service shutdown: root path changed (renamed or deleted)

**Comment by julianmesa-gitkraken** [comment]
> It works. I've received the following error: Service shutdown: root path changed (renamed or deleted)

Great. I will try to get the PR merged ASAP.
Thks for testing.

**Comment by julianmesa-gitkraken** [comment]
Fixed in [PR170](https://github.com/Axosoft/nsfw/pull/170)
