### ISSUE TITLE
Determine multiple file transfer has completed

### ISSUE THREAD

**Issue by adrianriddle** [Axosoft/nsfw#17]
Would it be possible to know if a file transfer is completed? 
For example if you are running over a slow SFTP connection and you are loading multiple files at once, is there a way to know that the entire transaction has completed? I am seeing the CREATED event and the MODIFIED events coming through and I am able to put in the delay to batch the events, but the problem would come in if the transfer of all the files takes longer than the delay for the batching.

**Comment by implausible** [comment]
For your use-case, do you know the size of the files that are coming in? You could leverage NSFW events to decide when to check the size of your file. When an event comes through you could debounce a check of the file size. Events will stop coming through and the debounce will fire one last time and confirm the size of your file.

I'm not entirely sure what information you have, but NSFW won't be enough to complete this task. I don't think we'll move to extend it in that direction either, as that is very use-case specific.
