### ISSUE TITLE
Ubuntu shared folder file watch fails

### ISSUE THREAD

**Issue by rmmoreira84** [Axosoft/nsfw#186]
Hello,

I'm using:
- NSFW@2.2.5;
- Ubuntu 22.04.5 LTS
- node 20.14.0

I've mounted a remote folder and I'm trying to monitor file changes.
Adding or removing a file from the share doesn't trigger anything on NSFW.

Does anyone have the same behavior?
Any suggestions?

Thank you.

**Comment by julianmesa-gitkraken** [comment]
Can you check if `inotifywait` works on that directory?
Does your code work on other directory?

**Comment by rmmoreira84** [comment]
Hi @julianmesa-gitkraken 

Thanks for the quick answer.
- I've tried monitoring a local directory and the same code, to that location, works properly;
- I'm not able to test the Inotifywait, I will test it tomorrow morning;

I don't know if it helps, but I also tested with chokidar and the notification of the events works properly.

Thank you.

**Comment by rmmoreira84** [comment]
Hi @julianmesa-gitkraken ,

I've validated and the inotifywait doesn't give any event when I add a new file on the share.
Do you think there can be any work around?

I've been debugging the code and, on the pollForEvents (NSFW.cpp), it doesn't surface any event on a shared folder.

Thanks for the help.

**Comment by julianmesa-gitkraken** [comment]
NSFW is based on inotify so there is no solution. I guess you need to use polling from filesystem as the manual says
