### ISSUE TITLE
Might be reasonable to pick a new name

### ISSUE THREAD

**Issue by vinyldarkscratch** [Axosoft/nsfw#20]
So I thought I should point out a little thing about the name of this particular program, and most likely at least one person on the team knows this.  NSFW is more commonly known as the abbreviation for "Not Safe For Work," which means explicit content (pornography and such).  Hope this helps if you guys don't want to create an accidental impression because of this, and that you got a good laugh from it.  ;P  (If it were intentionally named as such, though, then my gosh, Axosoft!  XD)

**Comment by implausible** [comment]
Aha, yes the name is intentional. We saw the opportunity for a more humorous name and took it :).

**Comment by vinyldarkscratch** [comment]
Well, in that case, it's a perfect name!  It's great to see humor of all types implemented in many programs.  X3
