### ISSUE TITLE
Crashes on Mac OS

### ISSUE THREAD

**Issue by implausible** [Axosoft/nsfw#21]
Details can be found here https://github.com/atom/github/issues/561

**Comment by BinaryMuse** [comment]
I was digging through the code today. Unfortunately I know very little about `CFRunLoop` and friends, but I'm wondering if it's possible that `started` gets set to true and then the destructor is called somehow before `RunLoop::work` is able to run (and set `mRunLoop` to a non-`NULL` value).

Or, if `mRunLoop` is already stopped/destroyed and `CFRunLoopStop` is choking on that (although it's interesting that `CFRunLoopIsWaiting` doesn't have a problem with it).

/cc @smashwilson

**Comment by implausible** [comment]
Hrmm. That's certainly possible. Investigating better synchronization around the start up logic may be the way to go. It's interesting though that the crashes always seem to center around the mutex blowing up though.

**Comment by implausible** [comment]
Ah I see, we have 2 sets of failures. One is located with CFRunLoopStop, which your order of events seems to fit. The other is a more mysterious one where the mutex is already destroyed or inaccessible by the time we syncWithWork in the destructor.

**Comment by implausible** [comment]
As far as CPU spiking goes, we should probably switch to using pthread signals to sync shutdown in osx.

**Comment by implausible** [comment]
@smashwilson @BinaryMuse let me know if the problem persists. I will have a release out when I get back in office on July 5th.

**Comment by implausible** [comment]
@smashwilson @BinaryMuse patch is out.
