### ISSUE TITLE
Linux: delete (via trash) is not reported as delete

### ISSUE THREAD

**Issue by bpasero** [Axosoft/nsfw#33]
**Steps:**
* use Linux (e.g. Ubuntu)
* delete a file via the native explorer (moves to trash)
=> no event for the delete is printed

It looks like chokidar is handling this properly, a `unlink` is reported and an `add` event when restoring the file.

**Comment by bpasero** [comment]
Interestingly as soon as I undo the delete via the native explorer, the events are all showing up: delete followed by create events.

**Comment by implausible** [comment]
That is really interesting. I'll look into it.

**Comment by MohamedLamineAllal** [comment]
I Report the same thing. Plus some other issues. In Debian, removing (moving to trash), first doesn't trigger anything. And when you remove the file from the trash, nsfw crash with the error "Uncaught Service shutdown unexpectedly"   (index.js line 62).  Same thing if you Undo the move to trash.

**Comment by implausible** [comment]
Hopefully this is handled properly now in https://www.npmjs.com/package/nsfw/v/1.2.0
