### ISSUE TITLE
Error installing on windows 10

### ISSUE THREAD

**Issue by wdamien** [Axosoft/nsfw#38]
When I first went to install this via `npm install nsfw`, MSBuild threw back a big nasty [build error](https://gist.github.com/wdamien/265701ef404d3cf49fd599038f4eb4a8). After a bit of research I found this [article](https://github.com/Microsoft/nodejs-guidelines/blob/master/windows-environment.md#compiling-native-addon-modules), then after running `npm install -g windows-build-tools` I was able to install `nsfw` normally.  

I don't know if this is something you can integrate into the `npm install`? Or at the very least a README mention would be helpful.

For reference:
node v6.11.1
windows: 10.0.15063 Build 15063

**Comment by dasmikko** [comment]
This should really be in the readme.

**Comment by sysrage** [comment]
Thank you. This tripped me up, as well. Seems that the build scripts aren't compatible with Python 3. Installing `windows-build-tools` gives you Python 2.7, which seems to work with the nsfw build scripts.

**Comment by implausible** [comment]
Native dependencies for Node require node-gyp. Details are provided here https://github.com/nodejs/node-gyp

**Comment by implausible** [comment]
I've updated the documentation.

**Comment by ingles98** [comment]
This is still an issue. Why would I have to do a whole setup for this dependency to work on each platform ? Shouldn't this be handled itself already by the install scripts ?
