### ISSUE TITLE
Linux: file move does not contain enough information to find out the target

### ISSUE THREAD

**Issue by bpasero** [Axosoft/nsfw#42]
When moving a file on Linux using the native file manager from one folder to another, the events that NSFW emits are:

```
{ action: 3,
    directory: '/home/ticino/development/vscode',
    oldFile: 'CODE_OF_CONDUCT.md',
    newFile: 'CODE_OF_CONDUCT.md' 
}
```

That however is not sufficient information to know where the file was moved to so it is impossible for a listener to properly react on this change. I would expect the `newFile` to contain the information to which folder the file was moved to.

**Comment by wmertens** [comment]
(Trying to determine if I can use this instead of chokidar, reviewing issues)

Action 3 seems to be rename, so it seems that the `rename` function call is being detected (yey!) but it doesn't handle the case where a rename goes across directories? (😢)

**Comment by etamponi** [comment]
Hello! Any news on this? Is it a limitation of the library on which nsfw is based? I am willing to help with a PR if possible!

**Comment by etamponi** [comment]
This PR fixes it for Linux: https://github.com/Axosoft/nsfw/pull/62

**Comment by implausible** [comment]
https://www.npmjs.com/package/nsfw/v/1.2.0
