### ISSUE TITLE
nsfw prevents Electron v4 apps from starting on Windows

### ISSUE THREAD

**Issue by jmrog** [Axosoft/nsfw#68]
`nsfw` currently specifies `"win_delay_load_hook": "false"` in its `binding.gyp` file. As of Electron v4, specifying this option/value combination prevents any app that uses `nsfw` from running on Windows; the app simply fails to start. Relevant explanation is here: https://electronjs.org/blog/electron-4-0#win_delay_load_hook

**Comment by implausible** [comment]
Thanks for bringing this to my attention! We will see what we can do.
