### ISSUE TITLE
Changes to directory reported as a file on Windows

### ISSUE THREAD

**Issue by damieng** [Axosoft/nsfw#9]
When watching for changes on Windows the underlying FS api reports both files and folders.

However the consumption code in ReadLoop only expects files because it splits the path it has been given based on the last separator into directory and file.  Which means when a folder changes it gets reported as a file.

I'd recommend not splitting the filename out if it is a directory being reported although this is kind of a breaking change as file would be undefined for these new type of events.

Also need to consider a directory rename. Should probably be oldDirectory and newDirectory.

You can repro this by monitoring for changes in a folder then doing `mkdir test` and you'll see;

``` json
{"action":0,"directory":"D:\\src\\nsfw-watcher","file":"test"}
```

**Comment by implausible** [comment]
Yes, NSFW is ignoring the difference between directory and files. At the time it was a simple abstraction, and for the original use of NSFW it was ok for this limitation to exist. Our needs in GitKraken didn't need this level of granularity, so I made a choice to skip it.

That said, I don't disagree that NSFW should increase it's capacities to report information. On all 3 operating systems I try to make the exact same API with the exact same output structure. It will need to be investigated what needs to occur to ensure all 3 OS can have the same level of granularity.

My biggest concern would be on the OSX side of things, which has been the most fickle file watching services. We want to make sure that any bump in the API comes from the file watching service at the OS level to keep the speed of the watcher intact.

**Comment by implausible** [comment]
For now, a workaround would be to stat your change list. Though I appreciate that may not be a permanent solution.

**Comment by damieng** [comment]
Our workaround for now has been to path.join new or changed files and then
fs.stat them to see if they are a directory or a file. Deletes would be
trickier.
